### ISSUE TITLE
Design improvements

### ISSUE THREAD

**Issue by pernillasterner** [pernillasterner/technigo-news-site#1]
**DESIGN FEEDBACK**
- When I see some call to action like buttons or links, I’d like to see that I am hovering it, and give the feel we are supposed to click on it (in addition to the cursor). I think it is always nice to have a little effect like a colour tone change  (from dark to light dark for example) or an underline

- If you have time, It would be nice to add a new feature where we can open a modal when we click on an image so the user can zoom in :slightly_smiling_face:

- A tiny note: when uploading images to a website, we should always think about the performance. I usually use this website to compress the files https://tinypng.com/ :relaxed: but here everything seems good :star2:
Overall, it is very clean and responsive, you did a fantastic job !

**TODOS**

- [ ] Add hover effect on buttons
- [ ] Create modal for images
- [ ] Check if images can be compressed
